version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: faculty-flow-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./resources/database:/docker-entrypoint-initdb.d
    ports:
      - "8080:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  faculty-flow-gateway:
    build:
      context: ../faculty-flow-gateway
    image: faculty-flow-gateway:latest
    container_name: faculty-flow-gateway
#    depends_on:
#      - faculty-flow-user
#      - faculty-flow-room
    ports:
      - "9000:8080"

  faculty-flow-user:
    build:
      context: ../faculty-flow-user
    image: faculty-flow-user:latest
    container_name: faculty-flow-user
#    depends_on:
#      postgres:
#        condition: service_healthy

  faculty-flow-room:
    build:
      context: ../faculty-flow-room
    image: faculty-flow-room:latest
    container_name: faculty-flow-room
#    depends_on:
#      postgres:
#        condition: service_healthy

volumes:
  pg_data:
