spring.security.enabled=false

management.endpoints.web.exposure.include=gateway
management.endpoint.gateway.enabled=true

management.endpoints.web.base-path=/actuator
spring.cloud.gateway.actuator.verbose.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://faculty-flow-user:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/user/**

spring.cloud.gateway.server.webflux.routes[1].id=room-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://faculty-flow-room:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/room/**