spring.security.enabled=false

spring.main.web-application-type=reactive

management.endpoints.web.exposure.include=gateway
management.endpoint.gateway.enabled=true
management.endpoints.web.base-path=/actuator
spring.cloud.gateway.actuator.verbose.enabled=true

# faculty-flow.service.front-end.url
faculty-flow.service.user.url=http://faculty-flow-user:8080
faculty-flow.service.room.url=http://faculty-flow-room:8080
faculty-flow.service.reservation.url=http://faculty-flow-reservation:8080

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=${faculty-flow.service.user.url}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/user/**

spring.cloud.gateway.server.webflux.routes[1].id=room-service
spring.cloud.gateway.server.webflux.routes[1].uri=${faculty-flow.service.room.url}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/room/**

spring.cloud.gateway.server.webflux.routes[2].id=reservation-service
spring.cloud.gateway.server.webflux.routes[2].uri=${faculty-flow.service.reservation.url}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/reservation/**

# Logging configuration
logging.level.org.springframework.web.cors=TRACE